[build]
builder = "nixpacks"
buildCommand = "cd backend && npm run build"

[deploy]
startCommand = "cd backend && npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure"

[phases.setup]
nixPkgs = ["nodejs", "postgresql"]

# Variável de ambiente para conexão com o banco de dados PostgreSQL
[env]
DATABASE_URL = "${{ Postgres.DATABASE_URL }}"